services:
  api:
    container_name: flavor-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - HOST=${HOST}
      - REDIS_PORT=${REDIS_EXPOSE_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE_TIME=${JWT_EXPIRE_TIME}
    ports:
      - ${PORT}:${PORT}
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    container_name: flavor-db
    image: postgres:16.3-alpine3.20
    restart: always
    ports:
      - ${POSTGRES_EXPOSE_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  redis:
    container_name: flavor-redis
    restart: always
    ports:
      - ${REDIS_EXPOSE_PORT}:6379

