services:
  api:
    extends:
      file: docker-compose.yml
      service: api
    networks:
      - flavor-network
    build:
      target: production
    environment:
      - NODE_ENV=production
  db:
    extends:
      file: docker-compose.yml
      service: db
    networks:
      - flavor-network
    volumes:
      - ./DATA/DB_DATA:/var/lib/postgresql/data
  redis:
    extends:
        file: docker-compose.yml
        service: redis
    image: redis/redis-stack-server:7.2.0-v10
    networks:
      - flavor-network
    volumes:
      - ./DATA/REDIS_DATA:/data

networks:
  flavor-network:
    name: flavor-network
    driver: bridge
