version: "3.8"

services:
  api:
    networks:
      - flavor-network
    build:
      target: development
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm run dev

networks:
  flavor-network:
    name: flavor-network
    driver: bridge
