version: "3.8"

services:
  api:
    container_name: flavor-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - NODE_ENV=development
    ports:
      - ${PORT}:${PORT}
