services:
  api:
    networks:
      - flavor-network
    build:
      target: development
    volumes:
      - ./:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm run dev
  db:
    networks:
      - flavor-network
    volumes:
      - ./DATA/DB_DATA:/var/lib/postgresql/data

networks:
  flavor-network:
    name: flavor-network
    driver: bridge
