version: "3.8"

services:
  api:
    extends:
      file: docker-compose.yml
      service: api
    networks:
      - flavor-network
    build:
      target: production
    environment:
      - NODE_ENV=production

networks:
  flavor-network:
    name: flavor-network
    driver: bridge
